version: '3.6'

services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.1-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=test_user
      - MARIADB_DATABASE=test_user
      - MARIADB_PASSWORD=test_user
  backend:
    tty: true
    image: docker.io/bitnami/laravel:7-debian-10
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=test_user
      - DB_DATABASE=test_user
      - DB_PASSWORD=test_user
    depends_on:
      - mariadb
    ports:
      - 8000:3000
    volumes:
      - ./backend/:/app
  frontend:
    image: node:12
    command: bash -c "yarn install && yarn dev"
    volumes:
      - ./frontend/:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - '3000:3000'
    depends_on:
        - backend
    environment:
      HOST: 0.0.0.0
